---
{{- if .Values.istio.virtualService.enabled -}}
{{- $fullName := include "ipinfo.fullname" . -}}
apiVersion: networking.istio.io/v1beta1
kind: DestinationRule
metadata:
  name: {{ $fullName }}
spec:
  host: {{ include "ipinfo.fullname" . }}.{{ .Release.Namespace}}.svc.cluster.local
  {{- with .Values.istio.virtualService.trafficPolicy }}
  trafficPolicy:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  subsets:
  - name: canary
    labels:
      app: {{ $fullName }}
  - name: stable
    labels:
      app: {{ $fullName }}
{{- end }}