apiVersion: v1
kind: Service
metadata:
  name: {{ include "ipinfo.fullname" . }}
  labels:
    {{- include "ipinfo.labels" . | nindent 4 }}
  {{- if .Values.istio.virtualService.enabled }}
  annotations:
    nginx.ingress.kubernetes.io/service-upstream: "true"
  {{- end }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  internalTrafficPolicy: Local
  selector:
    {{- include "ipinfo.selectorLabels" . | nindent 4 }}
